fleetops {
  storage {
    raw = "data/raw"
    bronze = "data/bronze"
    silver = "data/silver"
    gold = "data/gold"
  }

  dataset {
    taxiType = "yellow"
    year = 2025
    month = 1
  }

  spark {
    appName = "FleetOps Analytics"
    master = "local[*]"
    shufflePartitions = 4
  }
}
